version: '3'

services:
    ruby:
        build: .
        container_name: sinatra_ssl
        ports:
            - "4567:4567"
        volumes:
            - ./webrick:/app
        working_dir: /app
        command: bundle exec ruby /app/sinatra.rb -o 0.0.0.0
