version: '3'

services:
    ruby:
        build: .
        container_name: sinatra_ssl
        ports:
            - "4567:4567"
        volumes:
            - ./puma:/app
        working_dir: /app
        command: bundle exec puma config.ru -b 'ssl://0.0.0.0:4567?key=/app/certs/pkey.pem&cert=/app/certs/cert.crt'
